[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["backend_rag_ia/tests"]
python_files = ["test_*.py"]
addopts = "-v -ra -q"
log_cli = true
log_cli_level = "INFO"

[tool.coverage.run]
source = ["backend_rag_ia"]
omit = [
    "tests/*",
    "**/__init__.py",
    "**/test_*.py"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError"
]
