[project]
name = "backend_rag_ia"
version = "0.1.0"
description = "Backend para sistema RAG com IA"
requires-python = ">=3.11"

[tool.ruff]
line-length = 100
target-version = "py311"

# Regras essenciais
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "RUF", # ruff-specific
]

# Ignorar alguns casos específicos
ignore = [
    "E501",  # line too long
]

# Configurações específicas
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # unused imports

[tool.ruff.isort]
known-first-party = ["backend_rag_ia"]
