
# Configurações do Ruff para verificação de código
[tool.ruff]
line-length = 100
target-version = "py311"

# Habilita todas as regras recomendadas
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "YTT", # flake8-2020
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "ISC", # flake8-implicit-str-concat
    "PIE", # flake8-pie
    "T20", # flake8-print
    "PT",  # flake8-pytest-style
    "Q",   # flake8-quotes
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "INT", # flake8-gettext
    "ARG", # flake8-unused-arguments
    "PGH", # pygrep-hooks
    "PL",  # pylint
    "TRY", # tryceratops
    "RUF", # ruff-specific rules
]

# Ignora algumas regras específicas
ignore = [
    "E501",    # line too long
    "PLR0913", # too many arguments
]

# Configurações específicas
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"] # unused imports

[tool.ruff.isort]
known-first-party = ["backend_rag_ia"]
