services:
  - type: web
    name: backend-rag-ai
    rootDir: backend-rag-ai
    env: docker
    dockerfilePath: Dockerfile
    dockerBuildContext: .
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: ENVIRONMENT
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache-distribuido
          property: connectionString
      - key: PORT
        value: 10000

  - type: redis
    name: cache-distribuido
    ipAllowList: []
    plan: starter

previews:
  generation: manual
  expireAfterDays: 3
