# Exported from Render on 2024-12-27T10:09:24Z
services:
  - type: web
    name: backend-rag-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py backend_rag_ia.main:app
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: WORKERS
        value: 4
      - key: TIMEOUT
        value: 120
      - key: LOG_LEVEL
        value: info
    autoDeploy: true
    domains:
      - backend-rag-ia.onrender.com
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1

  - type: redis
    name: cache-distribuido
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: allkeys-lru

# Configuração de previews
previews:
  enable: true
  spec:
    inheritEnvVars: true
    envVars:
      - key: ENVIRONMENT
        value: preview
      - key: DEBUG
        value: true
    plan: starter

version: "1"
