# Exported from Render on 2024-12-27T10:09:24Z
services:
  - type: web
    name: backend-rag-ia
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /api/v1/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /app
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port 10000
version: "1"
