services:
  - type: web
    name: seu-servico
    rootDir: backend_rag_ia
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
