# Exported from Render on 2024-12-27T10:09:24Z
services:
  - type: web
    name: backend-rag-ia
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache-distribuido
          property: connectionString

  - type: redis
    name: cache-distribuido
    ipAllowList: [] # Apenas serviços internos
    plan: starter # Plano com persistência

# Configuração de previews
previews:
  # Habilita previews automáticos para todos os PRs
  enable: true
  # Configurações específicas para os previews
  spec:
    # Usa as mesmas configurações do serviço principal
    inheritEnvVars: true
    # Adiciona variáveis específicas para ambiente de preview
    envVars:
      - key: ENVIRONMENT
        value: preview
      - key: DEBUG
        value: true
    # Configurações de recursos para os previews
    plan: starter

version: "1"
