# Exported from Render on 2024-12-27T10:09:24Z
services:
  - type: web
    name: backend-rag-ia
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /
    buildCommand: ./build.sh
    startCommand: uvicorn backend_rag_ia.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: OPERATION_MODE
        value: render
      - key: IS_RENDER
        value: true
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
    dockerfilePath: ./Dockerfile
version: "1"
