services:
  - type: web
    name: oraculo-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn oracle:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    cors:
      allowOrigins:
        - "http://localhost:3000"
        - "http://localhost:5173"
        - "https://oraculo-asimov.vercel.app"
