# Exported from Render on 2024-12-27T10:09:24Z
databases:
  - name: vector_store
    databaseName: embeddings
    user: postgres
    plan: starter
    postgresMajorVersion: 15
    ipAllowList: []
    extensions:
      - vector

  - name: cache
    type: redis
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: allkeys-lru

services:
  - type: web
    name: backend-rag-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py backend_rag_ia.main:app
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: WORKERS
        value: 4
      - key: TIMEOUT
        value: 120
      - key: LOG_LEVEL
        value: info
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: VECTOR_STORE_TYPE
        value: pgvector
      - key: EMBEDDINGS_MODEL
        value: text-embedding-ada-002
      - key: MAX_TOKENS
        value: 8192
      - key: CHUNK_SIZE
        value: 1000
      - key: CHUNK_OVERLAP
        value: 200
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1

# Configuração de previews
previews:
  enable: true
  spec:
    inheritEnvVars: true
    envVars:
      - key: ENVIRONMENT
        value: preview
      - key: DEBUG
        value: true
    plan: starter

version: "1"
