# Exported from Render on 2024-12-27T10:09:24Z
services:
  - type: web
    name: oraculo-back-api
    env: docker
    dockerfilePath: ./clusters_back_API/oraculo_back_API/Dockerfile
    dockerContext: .
    pullRequestPreviewsEnabled: true
    autoDeploy: false
    plan: starter
    region: oregon
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
version: "1"
