# Exported from Render on 2024-12-27T10:09:24Z
services:
  - type: web
    name: backend-rag-ia
    runtime: docker
    repo: https://github.com/diegofornalha/backend-rag-ia
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: LANGCHAIN_CACHE_DIR
        sync: false
      - key: LANGCHAIN_PROJECT
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_ENDPOINT
        sync: false
      - key: LANGCHAIN_TRACING_V2
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: "1"
