-- Cria a tabela de estatísticas
CREATE TABLE IF NOT EXISTS statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value INTEGER NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Cria índice para busca rápida por chave
CREATE INDEX IF NOT EXISTS idx_statistics_key ON statistics(key);

-- Função para atualizar o timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop the trigger if it exists
DROP TRIGGER IF EXISTS update_statistics_updated_at ON statistics;

-- Trigger para atualizar o timestamp
CREATE TRIGGER update_statistics_updated_at
    BEFORE UPDATE ON statistics
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insere a contagem inicial de documentos
INSERT INTO statistics (key, value)
VALUES ('documents_count', 0)
ON CONFLICT (key) DO NOTHING; 