services:
  - type: web
    name: oraculo-back-api
    env: docker
    rootDir: clusters_back_API/oraculo_back_API
    region: oregon
    plan: starter
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: WORKERS
        value: 4
      - key: LOG_LEVEL
        value: INFO
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
