name: Code Quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/code-quality.yml"

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pylint mypy isort bandit safety

      - name: Check code formatting
        run: black --check .

      - name: Check imports
        run: isort --check-only --diff .

      - name: Run linting
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pylint $(git ls-files '*.py')

      - name: Type checking
        run: mypy --ignore-missing-imports .

      - name: Security check
        run: bandit -r .

      - name: Check dependencies for known vulnerabilities
        run: safety check

      - name: Verify requirements.txt
        run: |
          pip check
          pip install -r requirements.txt
          pip check
